# Generated by Django 6.0.7 on 2026-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, help_text='Uploaded video file (MP4, WebM, max 50MB)', null=True, upload_to='blogs/videos/'),
        ),
    ]
